apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: martinsops
        image: martinsops/myapp:v1.0
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent