apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world-app-monitor
  labels:
    team: ignitedev
spec:
  selector:
    matchLabels:
      app: hello-world-app
  endpoints:
  - port: http
    interval: 30s